server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://20.104.185.231:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://20.104.185.231:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://20.104.185.231:1003
    cart:
      path: /cart/**
      url: http://20.104.185.231:1004/api/v1
